name: fetching-releases
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  update-sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: ./fetch-releases.py
      - uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: "ci: Update sources.json"
