name: nix-checker

on:
  push:

jobs:
  run-nix-check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Install Nix
        uses: cachix/install-nix-action@v31.0.6
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run nix flake check
        run: nix flake check --all-systems
