name: ver-1-42-0-checker
on:
  push:
permissions: {}
jobs:
  run-nix-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run nix-shell
        run: nix-shell
